# Generated by Django 5.2.7 on 2025-12-02 20:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='actionlog',
            table='ActionLog',
        ),
        migrations.AlterModelTable(
            name='booking',
            table='Booking',
        ),
        migrations.AlterModelTable(
            name='facility',
            table='Facility',
        ),
        migrations.AlterModelTable(
            name='notification',
            table='Notification',
        ),
        migrations.AlterModelTable(
            name='product',
            table='Product',
        ),
        migrations.AlterModelTable(
            name='profile',
            table='Profile',
        ),
        migrations.AlterModelTable(
            name='role',
            table='Role',
        ),
        migrations.AlterModelTable(
            name='room',
            table='Room',
        ),
        migrations.AlterModelTable(
            name='roomavailability',
            table='RoomAvailability',
        ),
        migrations.AlterModelTable(
            name='roomfeature',
            table='RoomFeature',
        ),
        migrations.AlterModelTable(
            name='roomroomfeature',
            table='RoomRoomFeature',
        ),
        migrations.AlterModelTable(
            name='roomtype',
            table='RoomType',
        ),
        migrations.AlterModelTable(
            name='user',
            table='User',
        ),
    ]
