# Generated by Django 6.0 on 2025-12-04 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking_app', '0002_alter_actionlog_table_alter_booking_table_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roomavailability',
            name='end_time',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='roomavailability',
            name='start_time',
            field=models.DateTimeField(),
        ),
    ]
